---
name: build
on:
  pull_request:
    branches:
      - "main"
    types:
      - edited
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - Dockerfile
      - hashicorp.asc
      
concurrency:
  group: build-${{ github.head_ref || github.run_id }}-1
  cancel-in-progress: true

jobs:
  build-container:
    runs-on: ubuntu-22.04
    steps:
      - name: set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.10.4
          
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: build final image
        uses: docker/build-push-action@v4
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          provenance: false
          sbom: true
          tags: localbuild/testimage:v1
          push: false
          builder: ${{ steps.buildx.outputs.name }}
          outputs: type=docker,dest=/tmp/images.tar
          
      - name: load docker image
        run: docker import /tmp/images.tar localbuild/testimage:v1
        
      - name: list images
        run: docker images
        
      - name: run image
        run: docker inspect localbuild/testimage:v1

      - name: store artifact
        uses: actions/upload-artifact@v3
        with:
          name: container-artifact
          path: /tmp/images.tar
