---
name: build
on:
  pull_request:
    branches:
      - "main"
    types:
      - edited
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - Dockerfile
      - hashicorp.asc
      
concurrency:
  group: security-${{ github.head_ref || github.run_id }}-1
  cancel-in-progress: true

jobs:
  build-container:
    runs-on: ubuntu-22.04
    steps:
      - name: build container
        uses: docker/build-push-action@v4
        with:
          provenance: true
          sbom: true
          tags: localbuild/testimage:${{ github.run_id }}-1
          push: false
          load: true
          outputs: type=docker,dest=/tmp/images.tar
          
      - name: store artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-${{ github.run_id }}-1
          path: /tmp/images.tar
