---
name: build
on:
  pull_request:
    branches:
      - "main"
    types:
      - edited
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - Dockerfile
      - hashicorp.asc
      
concurrency:
  group: build-${{ github.head_ref || github.run_id }}-1
  cancel-in-progress: true

jobs:
  build-container:
    runs-on: ubuntu-22.04
    steps:
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: build container
        uses: docker/build-push-action@v4
        with:
          load: true
          sbom: true
          tags: localbuild/testimage:v1
          push: false
          outputs: dest=/tmp/images.tar
          
      - name: store artifact
        uses: actions/upload-artifact@v3
        with:
          name: container-artifact
          path: /tmp/images.tar
