---
name: build
on:
  pull_request:
    branches:
      - main
    types:
      - edited
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - Dockerfile
      - hashicorp.asc
      
concurrency:
  group: build-${{ github.head_ref || github.run_id }}-1
  cancel-in-progress: true

jobs:
  build-container:
    runs-on: ubuntu-22.04
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.10.4
          driver: docker-container
          driver-opts: network=host

      - name: build image
        uses: docker/build-push-action@v4
        id: image-output
        with:
          provenance: true
          sbom: true
          platforms: linux/amd64
          tags: localhost:5000/localbuild/testimage:v1
          push: true
          builder: ${{ steps.buildx.outputs.name }}

      - name: pull image
        run: docker pull localhost:5000/localbuild/testimage:v1

      - name: export image
        run: docker save -o /tmp/images.tar localhost:5000/localbuild/testimage:v1
          
      - name: list images
        run: docker images

      - name: store artifact
        uses: actions/upload-artifact@v3
        with:
          name: container-artifact
          path: /tmp/images.tar
