name: check terraform release
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

env:
  TEST_TAG: chaoscypher/minimal-terraform:test

jobs:
  check-new-release:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: build local container
        uses: docker/build-push-action@v3
        with:
          tags: ${{ env.TEST_TAG }}
          push: false
          load: true

      - name: get local terraform version
        id: terraform-local-verison
        run: docker run ${{ env.TEST_TAG }} -version -json
        shell: sh

      - name: get latest upstream terraform version
        id: terraform-upstream-version
        uses: actions/github-script@v6.3.2
        with:
          results-encoding: string
          script: |
            const terraform_url = https://checkpoint-api.hashicorp.com/v1/check/terraform
            const result = await github.request(terraform_url)
            const local_terraform_version = "${{ fromJson(steps.terraform-local-version.outputs.result).terraform_version }}"
            const upstream_terraform_version = result.data.current_version
            
            if (upstream_terraform_version > local_terraform_version) {
              console.log("Newer version of terraform found.")
            } else {
              console.log("Local version of terraform is latest.")
            }
