---
name: test container
on:
  pull_request:
    branches:
      - "main"
    types:
      - edited
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - Dockerfile

concurrency:
  group: no-test-${{ github.head_ref || github.run_id }}-1
  cancel-in-progress: true

jobs:
  functional-test:
    runs-on: ubuntu-22.04
    steps:
      - run: 'echo "functional-test job not required."'
