name: publish docker image
on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - Dockerfile
      - hashicorp.asc

permissions:
  contents: read
  packages: write

jobs:
  publish-image:
    if: github.event.pull_request.merged
    runs-on: ubuntu-22.04
    needs: auto-semver-release
    steps:
      - name: log in to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: log in to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ github.actor }}/minimal-terraform:latest
            ghcr.io/${{ github.actor }}/minimal-terraform:main
            ${{ github.actor }}/minimal-terraform:${{ needs.auto-semver-release.outputs.version }}
            ghcr.io/${{ github.actor }}/minimal-terraform:${{ needs.auto-semver-release.outputs.version }}
