name: quality check
on:
  pull_request:
    branches:
      - "main"
    types:
      - edited
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ci-${{ github.head_ref || github.run_id }}-1
  cancel-in-progress: true

jobs:
  quality-checks:
    runs-on: ubuntu-22.04
    steps:
      - name: lint code base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
