---
name: security check
on:
  pull_request:
    branches:
      - "main"
    types:
      - edited
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - Dockerfile

concurrency:
  group: security-${{ github.head_ref || github.run_id }}-1
  cancel-in-progress: true

jobs:
  build-container:
    runs-on: ubuntu-22.04
    steps:
      - name: build container
        uses: docker/build-push-action@v4
        with:
          tags: localbuild/testimage:${{ github.run_id }}-1
          push: false
          load: true

  cve-scan:
    runs-on: ubuntu-22.04
    needs: build-container
    steps:
      - name: cve scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: localbuild/testimage:${{ github.run_id }}-1
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  publish-sbom:
    runs-on: ubuntu-22.04
    needs: [build-container, cve-scan]
    steps:
      - name: publish sbom
        uses: anchore/sbom-action@v0
        with:
          artifact-name: sbom.spdx
          image: localbuild/testimage:${{ github.run_id }}-1
          output-file: sbom.json
          format: spdx-json
