name: quality check
on:
  pull_request:
    branches:
      - "main"
    types:
      - edited
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - Dockerfile

concurrency:
  group: ci-${{ github.head_ref || github.run_id }}-1
  cancel-in-progress: true

jobs:
  security-checks:
    runs-on: ubuntu-22.04
    steps:
      - name: build local container
        uses: docker/build-push-action@v2
        with:
          tags: localbuild/testimage:${{ github.head_ref }}
          push: false
          load: true

      - name: cve scan container
        uses: anchore/scan-action@v3
        with:
          image: localbuild/testimage:${{ github.head_ref }}
          fail-build: true
          severity-cutoff: high
