---
name: security check
on:
  pull_request:
    branches:
      - "main"
    types:
      - edited
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - Dockerfile
      - hashicorp.asc

concurrency:
  group: security-${{ github.head_ref || github.run_id }}-1
  cancel-in-progress: true

jobs:
  load-container:
    runs-on: ubuntu-22.04
    steps:
      - name: fetch image artifact
        uses: actions/download-artifact@v3
        with:
          name: container-artifact
          path: /tmp/images.tar
          
      - name: load images
        run: docker load --input /tmp/images.tar
          
  cve-scan:
    runs-on: ubuntu-22.04
    needs: load-container
    steps:
      - name: cve scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: localbuild/testimage:v1
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
