---
name: test container
on:
  pull_request:
    branches:
      - "main"
    types:
      - edited
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - Dockerfile

concurrency:
  group: test-${{ github.head_ref || github.run_id }}-1
  cancel-in-progress: true

jobs:
  functional-test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: build local container
        uses: docker/build-push-action@v3
        with:
          tags: "localbuild/testimage:${{ github.head_ref }}"
          push: false
          load: true

      - name: test entrypoint
        uses: "docker://localbuild/testimage:${{ github.head_ref }}"
        with:
          args: --version
